### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by JGNi** [meichthys/uptime_kuma#1]
It's not working. Keeps getting this error:
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/uptime_kuma/config_flow.py:55
Integration: Uptime Kuma
First occurred: 23:32:25 (1 occurrences)
Last logged: 23:32:25

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uptime_kuma_monitor.py", line 30, in update
    response = requests.get(
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '10.0.0.211:3001/metrics'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 166, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 111, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/uptime_kuma/config_flow.py", line 55, in async_step_user
    utkm = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/uptime_kuma_monitor.py", line 26, in __init__
    self.update()
  File "/usr/local/lib/python3.9/site-packages/uptime_kuma_monitor.py", line 41, in update
    raise UptimeKumaError(
uptime_kuma_monitor.UptimeKumaError: Could not fetch Uptime Kuma metrics: No connection adapters were found for '10.0.0.211:3001/metrics'

**Comment by m1ckyb** [comment]
When setting up, In the host/url config box, have you put the url as http://10.0.0.211, i'm sure you need to specify http://

**Comment by JOHLC** [comment]
> When setting up, In the host/url config box, have you put the url as http://10.0.0.211, i'm sure you need to specify http://

I was having this same issue and adding https:// resolved for me.
