### ISSUE TITLE
unable to connect to kuma

### ISSUE THREAD

**Issue by Johnny5AtGithub** [meichthys/uptime_kuma#111]
Hi,

I’ve just installed your addon through HACS, but I've been trying and trying to connect to my uptime kuma without any success. To be fair, at first I used my accounts' password, before I found the instructions and saw that I needed an API key. So I made that API key. Unfortunately, it still keeps saying it could not connect immediately. I played around a bit with or without `http://` but nothing had any effect. Then I went to the HA logs and I found this.

It looks to me like a syntax error embedded in the source code or something. Any idea how to resolve this?

```
Logger: custom_components.uptime_kuma
Source: custom_components/uptime_kuma/config_flow.py:58
integration: Uptime Kuma ([documentation](https://github.com/meichthys/uptime_kuma/blob/main/README.md), [issues](https://github.com/meichthys/uptime_kuma/issues))
First occurred: 09:25:13 (1 occurrences)
Last logged: 09:25:13

could not convert string to float: 'html>'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/prometheus_client/parser.py", line 115, in _parse_sample
    label_start, label_end = text.index("{"), text.rindex("}")
                             ^^^^^^^^^^^^^^^
ValueError: substring not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/uptime_kuma/config_flow.py", line 58, in _validate_input
    await uptime_robot_api.async_get_monitors()
  File "/usr/local/lib/python3.12/site-packages/pyuptimekuma/decorator.py", line 68, in wrapper
    response = UptimeKumaApiResponse.from_prometheus(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyuptimekuma/models.py", line 76, in from_prometheus
    for family in parsed:
  File "/usr/local/lib/python3.12/site-packages/prometheus_client/parser.py", line 14, in text_string_to_metric_families
    yield from text_fd_to_metric_families(StringIO.StringIO(text))
  File "/usr/local/lib/python3.12/site-packages/prometheus_client/parser.py", line 210, in text_fd_to_metric_families
    sample = _parse_sample(line)
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/prometheus_client/parser.py", line 133, in _parse_sample
    value, timestamp = _parse_value_and_timestamp(text[name_end:])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/prometheus_client/parser.py", line 107, in _parse_value_and_timestamp
    value = float(values[0])
            ^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'html>'
```

**Comment by Johnny5AtGithub** [comment]
The unsung HERO!!!!
It's the trailing slash!!!

https://github.com/meichthys/uptime_kuma/issues/55#issuecomment-2035823765

So, for the record, when in the chrome browser you always show full URL enabled (right click in the URL bar) and you select your URL **WITHOUT** a trailing slash, control+c copies your URL **WITH A SLASH**!!!

**Comment by mrlopezco** [comment]
Crazy... the trailing slash!
